### ISSUE TITLE
Ghost file, not visible in foxfile UI but visible when downloading a .rar

### ISSUE THREAD

**Issue by Luciano2572** [villa7/FoxFile#1]
File comes with the scrambled name when downloaded in .rar, its an extra file as even the GUI says i have 26 files, and .rar has 27 files.
Ghost file

**Comment by villa7** [comment]
files and db were out of sync from broken days, I fixed it for you :p

**Comment by Luciano2572** [comment]
10/10 support would recomend villa7 hosting
issue is fixed
thanks
illuminati
10/10 = 1
illuminati has 1 eye
dam dam
