### ISSUE TITLE
FoxFile = Iluminati!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Luciano2572** [villa7/FoxFile#2]
FoxFile has 7 letters. Fox is orange usually. Orange has 6 letters. Orange is a fruit. Fruits comes from Jesus. Jesus has 5 letters. Foxfile has 7 letters. 7 - 5 = 2. Theres 2 capital letters in FoxFile, 2/2 = 1. Iluminati has 1 eye. FoxFile = Iluminati

Another proof
Foxfile is orange theme default. Orange is food. Food was created by the holy creature. Bread is also food. Bread was insanely duplicated by the holy creature in the bible. Bible is old. Iluminati is an old cult, too. Coincidence? Lets keep going. Bread has 5 letters. Steak also has 5 letters. Steak comes from animals, which have been killed by humans since long time. Humans has 6 letters. FoxFile has 7. 7 - 6 = 1. Iluminatti has 1 eye. For the last pruf, Steak is food. food has 4 letters. Foxfile has 7. 7 - 4 = 3. THe triangle has 3 sides. Illuminati confirmed
10/10

**Comment by villa7** [comment]
10/10
