### ISSUE TITLE
Public folder would be nice

### ISSUE THREAD

**Issue by Luciano2572** [villa7/FoxFile#3]
Iluminati likes public folder, iluminati is about sharing.

A thing where a public folder, the user could access the folder with the whole GUI but not logged in would be nice. Like, when you are using a folder ya know, you have all the fancy download single file or download whole folder. But if hierarchy is like Public -> a, b, c, d and i gave user U1 A, he cannot download public entirely nor can he access b,c,d without link (.. or cracking it for that matter)

Cheers illuminati team

**Comment by villa7** [comment]
share system added
