### ISSUE TITLE
Shared error code

### ISSUE THREAD

**Issue by Luciano2572** [villa7/FoxFile#4]
Warning: file_get_contents(includes/sharedpage.php): failed to open stream: No such file or directory in F:\xampp\htdocs\FoxFile\dbquery.php on line 1160

Dis happens on shared tab

**Comment by villa7** [comment]
shared files page does not exist yet, is in progress

**Comment by Luciano2572** [comment]
Oh oki
Many thanks
Great support
Even tho illuminati is confirmed

**Comment by Luciano2572** [comment]
Foxfile > dropbox
