### ISSUE TITLE
Uploading multiple folders at once

### ISSUE THREAD

**Issue by Luciano2572** [villa7/FoxFile#6]
I don't know the feasibility of this (As I don't think I saw it on other companies such as dropbox), but a nice feature that would make me give dis 11/10 is
ability to select a bunch of folders, and foxfile would recreate the files with the apropriate content at cloud 
(eg local folder: Pics, with folders Pics june, Pics july, Pics december inside, each containing a few files. Uploading Pics would create the same Pics folder, with Pics june, pics july and pics december on the server w/ the inner files)

Cheers,
Luc again

**Comment by villa7** [comment]
I know Google Drive can do this, but I dont know how. Currently dropzone.js does not support uploading folders.
I did try to add this at one point, but couldn't figure out how :p

**Comment by Luciano2572** [comment]
Oh ok
Thanks tho!


2015-06-23 15:34 GMT-03:00 Theodore Kluge <notifications@github.com>:

**Comment by villa7** [comment]
I figured out how and this has now been added
